CREATE SEQUENCE vehiclepark_id_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 1;
ALTER TABLE VEHICLEPARK
ALTER COLUMN park_id
SET DEFAULT nextval('vehiclepark_id_seq');
--

CREATE SEQUENCE camp_id_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 1;
ALTER TABLE CAMPLOCATION
ALTER COLUMN camp_id
SET DEFAULT nextval('camp_id_seq');
--

CREATE SEQUENCE parking_id_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 1;
ALTER TABLE PARKINGAREA
ALTER COLUMN parking_id
SET DEFAULT nextval('parking_id_seq');
--

CREATE SEQUENCE customer_id_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 1;
ALTER TABLE CUSTOMER
ALTER COLUMN customer_id
SET DEFAULT nextval('customer_id_seq');
--

CREATE SEQUENCE staff_id_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 1;
ALTER TABLE STAFF
ALTER COLUMN staff_id
SET DEFAULT nextval('staff_id_seq');
--

CREATE SEQUENCE vehicle_id_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 1;
ALTER TABLE VEHICLE
ALTER COLUMN vehicle_id
SET DEFAULT nextval('vehicle_id_seq');
--

CREATE SEQUENCE reservation_id_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 1;
ALTER TABLE RESERVATION
ALTER COLUMN reservation_id
SET DEFAULT nextval('reservation_id_seq');
--

CREATE SEQUENCE price_id_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE CACHE 1;
ALTER TABLE price
ALTER COLUMN price_id
SET DEFAULT nextval('price_id_seq');